[package.metadata.android]
package = "com.saga.journal"
build_targets = ["aarch64-linux-android"]

[package.metadata.android.sdk]
min_sdk_version = 30
target_sdk_version = 36

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"